Revert "Try to update fedora base image"
Addressing:
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f81daf3388b]

runtime stack:
runtime.throw(0x10c5812, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:704 +0x4ac

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xcb0a90, 0xc00028b358, 0xc0000b4a90)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00028b328 sp=0xc00028b2f0 pc=0x405f7b
os/user._Cfunc_mygetpwuid_r(0x3c40a6f0, 0xc000364420, 0x574acc0, 0x400, 0xc0000b4a90, 0x7f8100000000)
	_cgo_gotypes.go:175 +0x4d fp=0xc00028b358 sp=0xc00028b328 pc=0x9a314d
os/user.lookupUnixUid.func1.1(0x3c40a6f0, 0xc000364420, 0xc0003431b0, 0xc0000b4a90, 0xc00028b3f8)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0xd0 fp=0xc00028b3a8 sp=0xc00028b358 pc=0x9a46b0
os/user.lookupUnixUid.func1(0xfe1660)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:103 +0x45 fp=0xc00028b3e0 sp=0xc00028b3a8 pc=0x9a4725
os/user.retryWithBuffer(0xc0003431b0, 0xc00028b4b8, 0xc0002e97f8, 0xc00033f628)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3e fp=0xc00028b438 sp=0xc00028b3e0 pc=0x9a3c7e
os/user.lookupUnixUid(0x3c40a6f0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:96 +0x132 fp=0xc00028b500 sp=0xc00028b438 pc=0x9a3592
os/user.current(0x7f82087687d0, 0x0, 0x9ab525)
	/usr/local/go/src/os/user/cgo_lookup_unix.go:49 +0x49 fp=0xc00028b540 sp=0xc00028b500 pc=0x9a3429
os/user.Current.func1()
	/usr/local/go/src/os/user/lookup.go:15 +0x25 fp=0xc00028b568 sp=0xc00028b540 pc=0x9a4565
sync.(*Once).doSlow(0x44a1ba0, 0x23db938)
	/usr/local/go/src/sync/once.go:66 +0xec fp=0xc00028b5b8 sp=0xc00028b568 pc=0x4853ac
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:57
os/user.Current(0xf993e0, 0xc000364390, 0x109ecd1)
	/usr/local/go/src/os/user/lookup.go:15 +0x105 fp=0xc00028b5e8 sp=0xc00028b5b8 pc=0x9a2e45
github.com/jackc/pgconn.defaultSettings(0xc000343150)
	/go/pkg/mod/github.com/jackc/pgconn@v1.6.4/config.go:350 +0x106 fp=0xc00028b6a0 sp=0xc00028b5e8 pc=0x9ab106
github.com/jackc/pgconn.ParseConfig(0xc0001dc960, 0x45, 0xc0001dc960, 0x4163dd, 0x10a40a6)
	/go/pkg/mod/github.com/jackc/pgconn@v1.6.4/config.go:192 +0x37 fp=0xc00028bad8 sp=0xc00028b6a0 pc=0x9a8d37
github.com/gobuffalo/pop/v5.urlParserPostgreSQL(0xc00033f2b0, 0xc000338c30, 0xc0001dc960)
	/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.2.4/dialect_postgresql.go:234 +0x53 fp=0xc00028bb68 sp=0xc00028bad8 pc=0xb04db3
github.com/gobuffalo/pop/v5.(*ConnectionDetails).withURL(0xc00033f2b0, 0x0, 0x0)
	/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.2.4/connection_details.go:82 +0x5ae fp=0xc00028bc78 sp=0xc00028bb68 pc=0xaf854e
github.com/gobuffalo/pop/v5.(*ConnectionDetails).Finalize(0xc00033f2b0, 0x0, 0x0)
	/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.2.4/connection_details.go:118 +0x225 fp=0xc00028bcd8 sp=0xc00028bc78 pc=0xaf8a05
github.com/gobuffalo/pop/v5.NewConnection(0xc00033f2b0, 0xc0003641b0, 0xc00028bda8, 0x0)
	/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.2.4/connection.go:50 +0x2f fp=0xc00028bd48 sp=0xc00028bcd8 pc=0xaf6f6f
github.com/gobuffalo/pop/v5.LoadFrom(0x249d3c0, 0xc00030d660, 0x173, 0xc00022f980)
	/go/pkg/mod/github.com/gobuffalo/pop/v5@v5.2.4/config.go:84 +0xfb fp=0xc00028be18 sp=0xc00028bd48 pc=0xaf661b
github.com/RedHatGov/ocdb/a.dropDatabaseYml()
	/go/src/github.com/RedHatGov/ocdb/a/aa.go:39 +0x19a fp=0xc00028bea0 sp=0xc00028be18 pc=0xb2607a
github.com/RedHatGov/ocdb/a.init.0()
	/go/src/github.com/RedHatGov/ocdb/a/aa.go:15 +0x26 fp=0xc00028bf28 sp=0xc00028bea0 pc=0xb25ce6
runtime.doInit(0x4441740)
	/usr/local/go/src/runtime/proc.go:5625 +0x8a fp=0xc00028bf58 sp=0xc00028bf28 pc=0x447e4a
runtime.doInit(0x4443e40)
	/usr/local/go/src/runtime/proc.go:5620 +0x57 fp=0xc00028bf88 sp=0xc00028bf58 pc=0x447e17
runtime.main()
	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc00028bfe0 sp=0xc00028bf88 pc=0x43ac45
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00028bfe8 sp=0xc00028bfe0 pc=0x46d9c1

This reverts commit b1744382d984181b6aa271ff095f038011e42144.